- name: Run Backend API Service
  docker_container:
    name: my-api
    image: gabriellft/tp-devops-simple-api:latest
    networks:
      - name: my-network
  vars:
    ansible_python_interpreter: /usr/bin/python3
